services:
  - type: web
    name: iman-ollama-server
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/tags
    envVars:
      - key: OLLAMA_ORIGINS
        value: "*"
      - key: PORT
        value: "11434"
